[build]
command = ""
publish = "."

[[headers]]
for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "interest-cohort=()"
